// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-music.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var search_music_default = defineTool({
  name: "search_music",
  title: "Search music",
  description: "Search Sentify's music catalog for songs, artists, or albums. Returns up to 20 matching tracks with title, artist, id, and duration.",
  inputSchema: {
    query: z.string().min(1).max(200).describe("Search query, e.g. 'Taylor Swift Blank Space'."),
    limit: z.number().int().min(1).max(20).optional().describe("Maximum number of results to return (default 10, max 20).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ query, limit }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!supabaseUrl || !publishableKey) {
      return {
        content: [{ type: "text", text: "Server not configured (missing Supabase env)." }],
        isError: true
      };
    }
    const cap = limit ?? 10;
    try {
      const url = new URL(`${supabaseUrl}/functions/v1/yt-search`);
      url.searchParams.set("q", query);
      url.searchParams.set("limit", String(cap));
      url.searchParams.set("category", "music");
      const res = await fetch(url.toString(), {
        headers: {
          Authorization: `Bearer ${publishableKey}`,
          apikey: publishableKey
        }
      });
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Search failed with status ${res.status}.` }],
          isError: true
        };
      }
      const data = await res.json();
      const items = Array.isArray(data?.items) ? data.items : [];
      const results = items.filter((r) => r?.type === "video").slice(0, cap).map((r) => ({
        id: r.id,
        title: r.title ?? "",
        artist: r.artist ?? "",
        durationSeconds: r.duration ?? null
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
        structuredContent: { results }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Search error: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool2({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity (user id, email) of the signed-in Sentify user associated with this MCP session.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail() ?? null,
      client_id: ctx.getClientId() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_sessions_default = defineTool3({
  name: "list_my_sessions",
  title: "List my devices",
  description: "List the signed-in Sentify user's active listening devices/sessions (device label, platform, last active).",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const supabaseUrl = process.env.SUPABASE_URL;
    const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient(supabaseUrl, publishableKey, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("user_sessions").select("id, device_label, platform, ip_city, ip_country, last_active_at, created_at").order("last_active_at", { ascending: false }).limit(50);
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to list sessions: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rumkfzvloeazpvyomhww";
var mcp_default = defineMcp({
  name: "sentify-mcp",
  title: "Sentify",
  version: "0.1.0",
  instructions: "Sentify's MCP server. Use `search_music` to find songs/artists in Sentify's catalog. Use `whoami` and `list_my_sessions` to inspect the signed-in user's account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_music_default, whoami_default, list_sessions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
